version: 0.2

phases:
  install:
    commands:
      - echo Install started on `date`
      - node -v && npm -v
      - curl -sL https://deb.nodesource.com/setup_9.x | sudo -E bash -
      - sudo apt-get install -y nodejs
      - npm i npm@latest -g --unsafe-perm
      - npm i @angular/cli@latest -g --unsafe-perm
      - node -v && npm -v && ng -v
  pre_build:
    commands:
      - echo Clean started on `date`
      - rm -rf dist
      - npm i
  build:
    commands:
      - echo Build started on `date`
      - ng build --prod
      - zip -r app.zip dist
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - app.zip
  discard-paths: yes
